const authActionTypes = {
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	SET_CURRENT_TOKEN: 'SET_CURRENT_TOKEN',
	SIGN_IN_START: 'SIGN_IN_START',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
	SIGN_OUT_START: 'SIGN_OUT_START',
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
	SIGN_UP_START: 'SIGN_UP_START',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
	EDIT__PROFILE__START: 'EDIT__PROFILE__START',
	EDIT__PROFILE__SUCCESS: 'EDIT__PROFILE__SUCCESS',
	EDIT__PROFILE__FAILURE: 'EDIT__PROFILE__FAILURE',
	FORGOT_PASSWORD_START: 'FORGOT_PASSWORD_START',
	FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
	FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',
	SIGN_UP_GET_COUNTRIES: 'SIGN_UP_GET_COUNTRIES',
	SIGN_UP_GET_COUNTRIES_FAILURE:'SIGN_UP_GET_COUNTRIES_FAILURE'
};
export default authActionTypes;
